export const jobListings = [
    {
      id: 1,
      title: "Full Stack Developer",
      company: "amazon",
      logo: "/placeholder.svg?height=60&width=60",
      postedTime: "24h Ago",
      experience: "1-3 yr Exp",
      locationType: "Onsite",
      salary: "12LPA",
      tag: "",
    },
    {
      id: 2,
      title: "Node Js Developer",
      company: "tesla",
      logo: "/placeholder.svg?height=60&width=60",
      postedTime: "24h Ago",
      experience: "1-3 yr Exp",
      locationType: "Onsite",
      salary: "12LPA",
      tag: "",
    },
    {
      id: 3,
      title: "UX/UI Designer",
      company: "design",
      logo: "/placeholder.svg?height=60&width=60",
      postedTime: "24h Ago",
      experience: "1-3 yr Exp",
      locationType: "Onsite",
      salary: "12LPA",
      tag: "",
    },
    {
      id: 4,
      title: "Full Stack Developer",
      company: "amazon",
      logo: "/placeholder.svg?height=60&width=60",
      postedTime: "24h Ago",
      experience: "1-3 yr Exp",
      locationType: "Onsite",
      salary: "12LPA",
      tag: "Govt Charge",
    },
    {
      id: 5,
      title: "Node Js Developer",
      company: "tesla",
      logo: "/placeholder.svg?height=60&width=60",
      postedTime: "24h Ago",
      experience: "1-3 yr Exp",
      locationType: "Onsite",
      salary: "12LPA",
      tag: "",
    },
    {
      id: 6,
      title: "UX/UI Designer",
      company: "design",
      logo: "/placeholder.svg?height=60&width=60",
      postedTime: "24h Ago",
      experience: "1-3 yr Exp",
      locationType: "Onsite",
      salary: "12LPA",
      tag: "Anonymous",
    },
    {
      id: 7,
      title: "Full Stack Developer",
      company: "amazon",
      logo: "/placeholder.svg?height=60&width=60",
      postedTime: "24h Ago",
      experience: "1-3 yr Exp",
      locationType: "Onsite",
      salary: "12LPA",
      tag: "",
    },
    {
      id: 8,
      title: "Node Js Developer",
      company: "tesla",
      logo: "/placeholder.svg?height=60&width=60",
      postedTime: "24h Ago",
      experience: "1-3 yr Exp",
      locationType: "Onsite",
      salary: "12LPA",
      tag: "",
    },
  ]